# Generated by Django 4.1.4 on 2023-01-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Comment',
        ),
    ]
