# Generated by Django 4.1.4 on 2023-01-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmoapi', '0002_rename_response_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTORequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.IntegerField()),
                ('justification', models.CharField(max_length=275)),
                ('is_approved', models.BooleanField(default=False)),
                ('cmouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapi.cmouser')),
                ('pto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmoapi.pto')),
            ],
        ),
    ]
